language: python

python:
    - "2.7"
    - "3.5"

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - deadsnakes

        packages:
            - g++-5
            - zlib1g-dev
            - libbz2-dev
            - python3.5-dev

env:
    - CC=g++-5 CXX=g++-5 BOOST_ROOT=$TRAVIS_BUILD_DIR/boost BOOST_LIBRARYDIR=$BOOST_ROOT/stage/lib LD_LIBRARY_PATH="$BOOST_LIBRARYDIR:$LD_LIBRARY_PATH"

install:
    - python travis.py
    - git clone https://github.com/romanvm/boost.git
    - chmod -R +x $BOOST_ROOT
    - cd $BOOST_ROOT
    - ./bootstrap.sh
    - ./b2 -j2 toolset=gcc-5 link=shared variant=release cxxflags=-fPIC --layout=system --with-regex --with-system --with-coroutine --with-context --with-filesystem --with-iostreams --with-date_time --with-python

script:
    - cd $TRAVIS_BUILD_DIR
    - python setup.py build test

notifications:
    email: false
