# Travis CI is used only to test for compile-time errors on GCC compiler.
# Currently Travis cannot produce a working build for functional tests
# because of its limitations.
language: python
python:
    - "2.7"
    #- "3.5"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - zlib1g-dev
            - libbz2-dev
env:
    - CC=g++-5 CXX=g++-5 BOOST_ROOT=$TRAVIS_BUILD_DIR/boost_1_61_0 BOOST_LIBRARYDIR=$BOOST_ROOT/stage/lib
before_install:
    - wget http://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fboost%2Ffiles%2Fboost%2F1.61.0%2F&ts=1465242714&use_mirror=vorboss
    - tar -xzvf boost_1_61_0.tar.gz
    - cd $BOOST_ROOT
    - sh bootstrap.sh
    - ./b2 link=static variant=release --layout=system --with-regex --with-system --with-coroutine --with-context --with-filesystem --with-iostreams --with-date_time
install:
    - echo "using python : $TRAVIS_PYTHON_VERSION ; " > ~/user-config.jam
    - cd $BOOST_LIBRARYDIR
    - rm -f libbost_python.a
    - cd $BOOST_ROOT
    - rm -rf bin.v2
    - ./b2 link=static variant=release --layout=system --with-python
script:
    - cd $TRAVIS_BUILD_DIR
    - python setup.py build install
    - cd test_wsgi_boost
    - python tests.py
notifications:
    email: false
