language: python
python:
    - "2.7"
    - "3.5"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
            #- george-edison55-precise-backports
        packages:
            - g++-5
            - libboost-coroutine1.55.0
            - libboost-coroutine1.55-dev
            - libboost1.55-all-dev
            - zlib1g-dev
env:
    - CC=g++-5 CXX=g++-5
install:
    - pip install requests
script:
    - python setup.py build
notifications:
    email: false
