# Travis CI is used only to test for compile-time errors on GCC compiler.
# Currently Travis cannot produce a working build for functional tests
# because of its limitations.
language: python
python:
    - "2.7"
    - "3.5"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - g++-5
            - libboost1.55-all-dev
            - zlib1g-dev
env:
    - CC=g++-5 CXX=g++-5
install: true
script:
    - python setup.py build
notifications:
    email: false
