version: "{build}"

os: Visual Studio 2015

platform: 
  - Win32

environment:
  global:
    MSVC_DEFAULT_OPTIONS: ON
    BOOST_ROOT: "%APPVEYOR_BUILD_FOLDER%\\boost"
    BOOST_LIBRARYDIR: "%BOOST_ROOT%\\stage\\lib"
    ZLIB_DIR: "%APPVEYOR_BUILD_FOLDER%\\zlib-1.2.8"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - cd %APPVEYOR_BUILD_FOLDER%
  - appveyor DownloadFile http://zlib.net/zlib128.zip
  - 7z e zlib128.zip -y
  - cd %ZLIB_DIR%
  - cmake .
  - cd %APPVEYOR_BUILD_FOLDER%
  - "git clone https://github.com/romanvm/boost.git"
  - python appveyor.py
  - cd %BOOST_ROOT%
  - bootstrap.bat
  - "b2 -j2 link=static runtime-link=static variant=release --with-regex --with-system --with-coroutine --with-context --with-filesystem --with-iostreams --with-date_time --with-python"


build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - python setup.py build

test_script:
  - python setup.py test
